apiVersion : v1
kind : PersistentVolumeClaim
metadata : 
  name : database-persistent-volume-claim
# Access Modes ReadWriteOnce, here Once = One Node that means
# One node can read and write
# And then raise a request for 2GB hard disk space
# Bottom line, we are asking kubernetes to give me 2GB space with 
# read write access  
spec : 
  accessModes :
    - ReadWriteOnce
  resources : 
    requests : 
      storage : 2Gi 