apiVersion : apps/v1
kind : Deployment
metadata : 
  name : server-deployment
spec : 
  replicas : 3
  selector : 
    matchLabels : 
      component : server
  template : 
    metadata : 
      labels : 
        component : server 
    spec : 
      containers : 
        - name : multi-server
          image : aishwaryaarun/multi-server
          ports : 
            - containerPort : 5000
          # Define Environment Variables   
          # Server Pod needs below variables to connect with Redis and Postgres
          env : 
            - name : REDIS_HOST
              value : redis-custer-ip-service
            - name : REDIS_PORT
              value : '6379'
            - name : PGUSER
              value : postgres
            - name : PGHOST
              value : postgres-client-ip-service
            - name : PGDATABASE
              value : postgres
            - name : PGPORT
              value : '5432'
            # Get the PGPASSWORD from Secrets (pgpassword)              
            - name : PGPASSWORD
              valueFrom :
                secretKeyRef : 
                  name : pgpassword
                  key : PGPASSWORD 
